version: '2'
services:
  lenses:
    image: 'landoop/kafka-lenses-dev'
    ports:
      - '3030:3030'
      - '9092:9092'
      - '2181:2181'
      - '8081:8081'
    environment:
      - 'ADV_HOST=127.0.0.1'
      - 'LICENSE_URL=https://dl.lenses.stream/d/?id=741f71d8-eb82-42ce-b82d-92cb1ac97962'
    network_mode: 'host'
#  zookeeper:
#    image: 'bitnami/zookeeper:latest'
#    ports:
#      - '2181:2181'
#    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
#  kafka:
#    image: 'bitnami/kafka:latest'
#    ports:
#      - '9092:9092'
#    environment:
#      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
#      - ALLOW_PLAINTEXT_LISTENER=yes
